
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FraudDetectionFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: FraudDetectionV2
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      MemorySize: 2048
      Timeout: 30
